In [61]:
import pandas as pd
import numpy as np
import json
from pathlib import Path
import requests

#Defining file paths
netflix_titles = Path("Resources/netflix_titles.csv")
ended_netflix_shows = Path("Resources/All Ended Netflix Original Shows.csv")

print(netflix_titles)

Resources\netflix_titles.csv

In [62]:
#Reading data files
netflix_titles_df = pd.read_csv(netflix_titles, encoding="ISO-8859-1")
ended_netflix_shows_df = pd.read_csv(ended_netflix_shows, encoding="ISO-8859-1")

ended_netflix_shows_df.head()

,Title,Genre,Premiere Date,Finale Date,Seasons,Cancelled
0,House of Cards,Political drama,"February 1, 2013","November 2, 2018",6,0
1,Orange Is the New Black,Comedy drama,"July 11, 2013","July 26, 2019",7,0
2,Marco Polo,Historical drama,"December 12, 2014","July 1, 2016",2,0
3,Bloodline,Thriller,"March 20, 2015","May 26, 2017",3,0
4,Daredevil,Superherolegal drama,"April 10, 2015","October 19, 2018",3,0

In [76]:
ended_netflix_shows_df["type"] = "TV Show"
ended_netflix_shows_df.head()

,title,Genre,Premiere Date,Finale Date,Seasons,Cancelled,type
0,House of Cards,Political drama,"February 1, 2013","November 2, 2018",6,0,TV Show
1,Orange Is the New Black,Comedy drama,"July 11, 2013","July 26, 2019",7,0,TV Show
2,Marco Polo,Historical drama,"December 12, 2014","July 1, 2016",2,0,TV Show
3,Bloodline,Thriller,"March 20, 2015","May 26, 2017",3,0,TV Show
4,Daredevil,Superherolegal drama,"April 10, 2015","October 19, 2018",3,0,TV Show

In [63]:
netflix_titles_df.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
netflix_titles_df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25'],
      dtype='object')

In [78]:
ended_netflix_shows_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1353 entries, 0 to 1352
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          1353 non-null   object
 1   Genre          1240 non-null   object
 2   Premiere Date  1353 non-null   object
 3   Finale Date    1353 non-null   object
 4   Seasons        1353 non-null   int64
 5   Cancelled      1353 non-null   int64
 6   type           1353 non-null   object
dtypes: int64(2), object(5)
memory usage: 74.1+ KB

In [90]:
ended_netflix_shows_df["Genre"].value_counts().describe()

count    311.000000
mean       3.987138
std       10.279317
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       93.000000
Name: count, dtype: float64

In [70]:
ended_netflix_shows_df.rename(columns={'Title': 'title'}, inplace=True)
ended_netflix_shows_df.columns

Index(['title', 'Genre', 'Premiere Date', 'Finale Date', 'Seasons',
       'Cancelled'],
      dtype='object')

In [75]:
test = pd.merge(ended_netflix_shows_df, netflix_titles_df, on='title', how='outer')
num_rows = len(test)
print(test)

                        title                 Genre      Premiere Date  \
0              House of Cards       Political drama   February 1, 2013
1     Orange Is the New Black          Comedy drama      July 11, 2013
2                  Marco Polo      Historical drama  December 12, 2014
3                   Bloodline              Thriller     March 20, 2015
4                   Daredevil  Superherolegal drama     April 10, 2015
...                       ...                   ...                ...
9367               Zombieland                   NaN                NaN
9368                     Zoom                   NaN                NaN
9369                   Zubaan                   NaN                NaN
9370       Parasyte: The Grey                   NaN                NaN
9371                   Serena                   NaN                NaN

           Finale Date  Seasons  Cancelled show_id     type         director  \
0     November 2, 2018      6.0        0.0   s1060  TV Show              NaN
1        July 26, 2019      7.0        0.0    s527  TV Show              NaN
2         July 1, 2016      2.0        0.0   s5837  TV Show              NaN
3         May 26, 2017      3.0        0.0   s5471  TV Show              NaN
4     October 19, 2018      3.0        0.0     NaN      NaN              NaN
...                ...      ...        ...     ...      ...              ...
9367               NaN      NaN        NaN   s8805    Movie  Ruben Fleischer
9368               NaN      NaN        NaN   s8806    Movie     Peter Hewitt
9369               NaN      NaN        NaN   s8807    Movie      Mozez Singh
9370               NaN      NaN        NaN   s8808  TV Show     Yeon Sang-ho
9371               NaN      NaN        NaN   s8809    Movie     Susanne Bier

                                                   cast  ... Unnamed: 16  \
0     Kevin Spacey, Robin Wright, Kate Mara, Corey S...  ...         NaN
1     Taylor Schilling, Kate Mulgrew, Laura Prepon, ...  ...         NaN
2     Lorenzo Richelmy, Benedict Wong, Chin Han, Joa...  ...         NaN
3     Kyle Chandler, Ben Mendelsohn, Sissy Spacek, L...  ...         NaN
4                                                   NaN  ...         NaN
...                                                 ...  ...         ...
9367  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  ...         NaN
9368  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  ...         NaN
9369  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...  ...         NaN
9370         Shin Hyun-been, Jeon Yeo-bin, Goo Kyo-hwan  ...         NaN
9371  Bradley Cooper, Jennifer Lawrence, Toby Jones,...  ...         NaN

     Unnamed: 17  Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22  \
0            NaN          NaN         NaN         NaN         NaN         NaN
1            NaN          NaN         NaN         NaN         NaN         NaN
2            NaN          NaN         NaN         NaN         NaN         NaN
3            NaN          NaN         NaN         NaN         NaN         NaN
4            NaN          NaN         NaN         NaN         NaN         NaN
...          ...          ...         ...         ...         ...         ...
9367         NaN          NaN         NaN         NaN         NaN         NaN
9368         NaN          NaN         NaN         NaN         NaN         NaN
9369         NaN          NaN         NaN         NaN         NaN         NaN
9370         NaN          NaN         NaN         NaN         NaN         NaN
9371         NaN          NaN         NaN         NaN         NaN         NaN

      Unnamed: 23  Unnamed: 24  Unnamed: 25
0             NaN          NaN          NaN
1             NaN          NaN          NaN
2             NaN          NaN          NaN
3             NaN          NaN          NaN
4             NaN          NaN          NaN
...           ...          ...          ...
9367          NaN          NaN          NaN
9368          NaN          NaN          NaN
9369          NaN          NaN          NaN
9370          NaN          NaN          NaN
9371          NaN          NaN          NaN

[9372 rows x 31 columns]